```{r knitsetup, echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}
opts_knit$set(base.dir='./', fig.path='', out.format='md')
opts_chunk$set(prompt=TRUE, comment='', results='markup')
# See yihui.name/knitr/options for more Knitr options.
##### Put other setup R code here

```

# Loop

## for-loop

```{r}
for(i in c(1,2,3)) {
  message("Hello, world!")
}

for(i in 1:10) {
  message(sprintf("Message %d",i))
}


for(i in 1:10) {
  if(i==5) break
  else message(sprintf("Message %d",i))
}

for(i in 1:10) {
  if(i==5) next
  else message(sprintf("Message %d",i))
}

for(item in c("Hello","World","Hi")) {
  message(item)
}

for(item in list(a=c(1,2,3),b=c("a","b","c","d"))) {
  str(item)
}

df <- data.frame(x=c(1,2,3),y=c("A","B","C"),stringsAsFactors = FALSE)
for(col in df) {
  str(col)
}

for(i in 1:nrow(df)) {
  row <- df[i,]
  str(row)
}

```

## while-loop

```{r}
x <- 0
while(x <= 10) {
  message(x)
  x <- x + 1
}
```

## repeat-loop

```{r}
x <- 0
repeat {
  x <- x+1
  if(x==10) break
  else if(x==5) {
    next
  }
  else {
    message(x)
  }
}
```

