```{r knitsetup, echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}
opts_knit$set(base.dir='./', fig.path='', out.format='md')
opts_chunk$set(prompt=TRUE, comment='', results='markup')
# See yihui.name/knitr/options for more Knitr options.
##### Put other setup R code here

```

# Matrix

## Defining a matrix

Create matrix from a vector.

```{r}
matrix(c(1,2,3,2,3,4,3,4,5),ncol = 3)

matrix(c(1,2,3,
         4,5,6,
         7,8,9),nrow=3,byrow=FALSE)

matrix(c(1,2,3,
         4,5,6,
         7,8,9),nrow=3,byrow=TRUE)
```

Create a diagonal matrix.

```{r}
diag(1,nrow=5)
```


## Naming rows and columns

```{r}
matrix(c(1,2,3,4,5,6,7,8,9),nrow=3,byrow=TRUE,
  dimnames=list(c("r1","r2","r3"),c("c1","c2","c3")))
```

```{r}
m1 <- matrix(c(1,2,3,2,3,4,3,4,5),ncol = 3)
rownames(m1) <- c("r1","r2","r3")
colnames(m1) <- c("c1","c2","c3")
```

## Subsetting matrix

```{r}
m1[1,]
m1[,2]
m1[1,1]
m1[1:2,]
m1[,2:3]
m1[1:2,2:3]
m1[-1,]
m1[,-2]
m1[1]
m1[9]
m1[3:7]
m1[c("r1","r3"),c("c1","c3")]
```

## Operators for matrices

```{r}
m1 + m1
m1 - 2*m1
m1 * m1
m1 / m1
m1^2
m1 %*% m1
t(m1)
```

